name=Botones
version=1.0.0
author=Ing. Mecatrónico Milton Elias Pech Uc
maintainer=Milton <milton.ortmed@gmail.com>
sentence=Librería para controlar botones pulsadores.
paragraph=Permite leer botones pulsadores de forma sencilla en proyectos ESP32.
category=Signal Input/Output
url=https://github.com/milton-ortmed/Botones
architectures=*
includes=Botones.hpp
